/** @type {import('tailwindcss').Config} */
export default {
  content: [
    './index.html',
    './src/**/*.{js,ts,jsx,tsx}',
  ],
  theme: {
    extend: {
      colors: {
        'on-tertiary-fixed': '#002113',
        'secondary': '#0051d5',
        'outline': '#76777d',
        'surface': '#f8f9ff',
        'on-error': '#ffffff',
        'secondary-fixed': '#dbe1ff',
        'surface-container-highest': '#d3e4fe',
        'surface-tint': '#565e74',
        'surface-container-low': '#eff4ff',
        'on-tertiary-container': '#009668',
        'primary-container': '#131b2e',
        'tertiary-fixed': '#6ffbbe',
        'inverse-on-surface': '#eaf1ff',
        'inverse-primary': '#bec6e0',
        'on-background': '#0b1c30',
        'on-secondary': '#ffffff',
        'outline-variant': '#c6c6cd',
        'secondary-fixed-dim': '#b4c5ff',
        'inverse-surface': '#213145',
        'on-secondary-fixed-variant': '#003ea8',
        'surface-dim': '#cbdbf5',
        'surface-variant': '#d3e4fe',
        'on-secondary-container': '#fefcff',
        'on-primary-fixed-variant': '#3f465c',
        'background': '#f8f9ff',
        'on-tertiary': '#ffffff',
        'surface-container-lowest': '#ffffff',
        'on-primary-container': '#7c839b',
        'primary': '#000000',
        'on-surface': '#0b1c30',
        'on-tertiary-fixed-variant': '#005236',
        'surface-container': '#e5eeff',
        'on-secondary-fixed': '#00174b',
        'surface-bright': '#f8f9ff',
        'tertiary-container': '#002113',
        'tertiary': '#000000',
        'on-error-container': '#93000a',
        'on-primary': '#ffffff',
        'primary-fixed': '#dae2fd',
        'error': '#ba1a1a',
        'surface-container-high': '#dce9ff',
        'on-surface-variant': '#45464d',
        'tertiary-fixed-dim': '#4edea3',
        'error-container': '#ffdad6',
        'primary-fixed-dim': '#bec6e0',
        'on-primary-fixed': '#131b2e',
        'secondary-container': '#316bf3',
      },
      borderRadius: {
        'DEFAULT': '0.25rem',
        'lg': '0.5rem',
        'xl': '0.75rem',
        'full': '9999px',
      },
      spacing: {
        'lg': '40px',
        'sm': '16px',
        'xs': '8px',
        'gutter': '24px',
        'max-width': '1280px',
        'base': '4px',
        'xl': '64px',
        'md': '24px',
        'margin-mobile': '16px',
      },
      fontFamily: {
        'label-sm': ['Geist', 'sans-serif'],
        'body-md': ['Inter', 'sans-serif'],
        'body-lg': ['Inter', 'sans-serif'],
        'headline-md': ['Geist', 'sans-serif'],
        'headline-lg': ['Geist', 'sans-serif'],
        'display-lg': ['Geist', 'sans-serif'],
        'headline-lg-mobile': ['Geist', 'sans-serif'],
        'label-md': ['Geist', 'sans-serif'],
      },
      fontSize: {
        'label-sm': ['12px', { lineHeight: '1.2', fontWeight: '600' }],
        'body-md': ['16px', { lineHeight: '1.5', fontWeight: '400' }],
        'body-lg': ['18px', { lineHeight: '1.6', fontWeight: '400' }],
        'headline-md': ['24px', { lineHeight: '1.4', fontWeight: '600' }],
        'headline-lg': ['32px', { lineHeight: '1.3', letterSpacing: '-0.01em', fontWeight: '600' }],
        'display-lg': ['48px', { lineHeight: '1.2', letterSpacing: '-0.02em', fontWeight: '700' }],
        'headline-lg-mobile': ['24px', { lineHeight: '1.3', fontWeight: '600' }],
        'label-md': ['14px', { lineHeight: '1.2', letterSpacing: '0.01em', fontWeight: '500' }],
      },
    },
  },
  plugins: [],
};
